INFO:mv-polar-bears:Queue WIND-SPEED-MPH -> 5.6 for row 1001
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/prj/mv-polar-bears/build_site.py in <module>()
    709     add_missing_days(sheet)
    710     add_missing_dows(sheet)
--> 711     add_missing_weather(sheet) # NOTE: expect unhandled rate failure
    712     add_missing_water(sheet)

~/prj/mv-polar-bears/build_site.py in wrapper(*args, **kwargs)
    112                 else:
    113                     # some other error, fail
--> 114                     raise err
    115 
    116             # completed without error

~/prj/mv-polar-bears/build_site.py in wrapper(*args, **kwargs)
     98             try:
     99                 # attempt to run function
--> 100                 func(*args, **kwargs)
    101 
    102             except Exception as err:

~/prj/mv-polar-bears/build_site.py in add_missing_weather(sheet)
    276             # get weather
    277             dt = parse_datetime(row['DATE'], row['TIME'])
--> 278             weather_data = get_weather_conditions(dt=dt)
    279             # queue update for all missing cells
    280             sheet_row_idx = ii + 2 # index in sheet, 1-based with header

~/prj/mv-polar-bears/build_site.py in get_weather_conditions(lon, lat, dt, key_file)
    384     params = {'units': 'us'}
    385     resp = requests.get(url, params)
--> 386     resp.raise_for_status()
    387     data = resp.json()
    388 

~/venv/mv-polar-bears/lib/python3.6/site-packages/requests/models.py in raise_for_status(self)
    933 
    934         if http_error_msg:
--> 935             raise HTTPError(http_error_msg, response=self)
    936 
    937     def close(self):

HTTPError: 403 Client Error: Forbidden for url: https://api.darksky.net/forecast/06496b3f94d98df6ba045ac2dacc3050/41.4524630000,-70.5535260000,1491049560?units=us

